[package]
name = "hzrd"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
ipnet = "2.11.0"
log = "0.4.27"
pretty_env_logger = "0.5.0"
pyo3 = { version = "0.24.1", features = ["auto-initialize"] }
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.20"
